doc/debugging.md
Add the steps required to wire a supported laptop for EC debugging,
along with setting up an environment to receive EC logs.
=> docs: Add documentation for debugging

src/board/system76/darp5/include/board/power.h, src/board/system76/darp5/kbscan.c, src/board/system76/darp5/pmc.c, src/board/system76/darp5/power.c, src/board/system76/galp3-c/include/board/power.h, src/board/system76/galp3-c/kbscan.c, src/board/system76/galp3-c/pmc.c, src/board/system76/galp3-c/power.c, src/board/system76/lemp9/include/board/power.h, src/board/system76/lemp9/kbscan.c, src/board/system76/lemp9/pmc.c, src/board/system76/lemp9/power.c
Expose power state so that a key event can wake the system from S3./
Resolves: #21
=> Wake from S3 using any key

src/board/system76/darp5/include/board/kbscan.h, src/board/system76/darp5/kbc.c, src/board/system76/darp5/kbscan.c, src/board/system76/galp3-c/include/board/kbscan.h, src/board/system76/galp3-c/kbc.c, src/board/system76/galp3-c/kbscan.c, src/board/system76/lemp9/include/board/kbscan.h, src/board/system76/lemp9/kbc.c, src/board/system76/lemp9/kbscan.c
Per [\[1\]], use a default delay of 500ms and a rate of 10.9 characters per second. When the Linux kernel starts, this will be updated by `atkbd` to the fastest settings possible [\[2\]]: 250ms delay and 30 CPS.
Modifying these values with `kbdrate` to test settings will cause two spurious ACKs in the kernel. This behavior is also present in the proprietary firmware.
Resolves: #19
[\[1\]]: https://web.archive.org/web/20180217074705/http://computer-engineering.org/ps2keyboard/
[\[2\]]: https://github.com/torvalds/linux/blob/c5f86891185c408b2241ba9a82ae8622d8386aff/drivers/input/keyboard/atkbd.c#L863-L868
=> Implement key repeat

src/board/system76/darp5/kbscan.c, src/board/system76/galp3-c/kbscan.c, src/board/system76/lemp9/kbscan.c
If a key press is detected that would trigger a ghost key, ignore the key.
Based on QMK implementation ([keyboard.c](https://github.com/qmk/qmk_firmware/blob/b892a1429d753d83d179fea26a2c7b84edab840d/tmk_core/common/keyboard.c#L129)).
Resolves: #24
=> Ignore key presses that trigger ghost keys

Makefile
In order to use the same version as the board firmware we need to be able to specify the version string for the EC.
Ref: system76/firmware-open#75
=> Allow overriding version

src/board/system76/darp5/power.c, src/board/system76/darp5/scratch.c, src/board/system76/galp3-c/power.c, src/board/system76/galp3-c/scratch.c, src/board/system76/lemp9/power.c, src/board/system76/lemp9/scratch.c, src/ec/it5570e/include/ec/bram.h, src/ec/it8587e/include/ec/bram.h
This adds a flag stored in battery-backed RAM that will cause the EC to power on automatically if it is not set to a magic value.
This flag is cleared when entering the scratch ROM, ensuring that the system automatically powers on when flashed.
=> Power on after reset from scratch rom

src/board/system76/lemp9/peci.c
This should lower fan noise, with a minor performance cost from the time it hits TCC to the time the fans spin, which on my testing was two seconds of minor frequency drop after 8 seconds of stressing.
=> Increase heatup time to 10 seconds and disable interpolation

src/board/system76/common/peci.c
This adjusts the fan curve to start at 70C instead of 65C, and max out at 60%. Tests with stress-ng indicate that this still is able to prevent thermal throttling, system is still able to run CPU above 20W power limit 1, and frequencies are as expected with a TDP-up system. Fan speeds of 40% and 75% were tested as well. 40% led to thermal runaway and lower performance (18W CPU power when thermals settled). 75% was overkill, kept CPU well below thermal throttling limit. 60% keeps the CPU indefinitely near the throttling limit while also maintaining 20W CPU power.
In short, the new maximum value of 60% is a goldilocks zone for quiet operation and high performance. It appears that users prefer increased heat to the jet aircraft noises this system makes at 100%. Please test that chassis …
=> lemp9: lower maximum fan speed

src/board/system76/common/kbscan.c
- Don't record a ghost key as pressed
- Debouce on ghost release to allow ghosts to settle.
- Reduce debounce time from 20ms to 15ms.
Signed-off-by: Evan Lojewski <github@meklort.com>
=> keymap: Allow ghost keys to be pressed once the ghost is removed

doc/debugging.md
Add battery pins used for I2C debugging on additional models. Change pin names to those used in laptop  service manuals.
=> docs: Add I2C pins for more models

README.md, doc/controllers.md, doc/debugging.md, doc/flashing.md, doc/mega2560.md
- Add a more comprehensive document describing the Mega 2560 and FPC breakout board
- Move flashing information to a separate file
- Point users to firmware-open for installing full set of dependencies
=> Docs update 

doc/flashing.md
A rather important bit of information users should be made aware of.
See also: #36
=> docs: Add note about system reset for internal flashing

src/board/system76/addw2/gpio.c, src/board/system76/addw2/include/board/gpio.h, src/board/system76/bonw14/gpio.c, src/board/system76/bonw14/include/board/gpio.h, src/board/system76/common/power.c, src/board/system76/darp5/gpio.c, src/board/system76/darp5/include/board/gpio.h, src/board/system76/galp3-c/gpio.c, src/board/system76/galp3-c/include/board/gpio.h, src/board/system76/gaze15/gpio.c, src/board/system76/gaze15/include/board/gpio.h, src/board/system76/lemp9/include/board/gpio.h, src/board/system76/oryp6/gpio.c, src/board/system76/oryp6/include/board/gpio.h
~Currently only works during S5.
Does not work during S3 (`LAN_WAKEUP#` not asserted; device disabled during sleep?).~
_Should_ work from S3 and S5 when magic packet wake support is enabled in the Ethernet controller.
1. Get the MAC address for the Ethernet adapter: `ip link [show <device>]`
2. Ensure it supports Wake-on-Lan: `sudo ethtool <device>  | grep Wake` (must have `g`)
3. Enable WoL: `sudo ethtool -s <device> wol g`
4. Power off target, plug in Ethernet cable
5. Send magic packet: `wol <mac-address>`
Target output:
```
[oryp6 ~]$ ip link show enp40s0
2: enp40s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
link/ether 80:fa:5b:80:dd:69 brd ff:ff:ff:ff:ff:ff
[oryp6 ~]$ sudo ethtool enp40s0 | grep Wake
Supports Wake-on: …
```
=> Wake-on-LAN

src/board/system76/common/acpi.c, src/board/system76/common/include/board/battery.h, src/board/system76/common/power.c
Don't turn on battery LEDs or report it connected if not initialized.
=> Add battery detection

src/board/system76/common/kbc.c
This command is described in https://www.win.tue.nl/~aeb/linux/kbd/scancodes-12.html#kcf6
It clears the LEDs and sets the repeat parameters back to their defaults
=> Add KBC 0xF6 command

src/board/system76/common/acpi.c, src/board/system76/common/battery.c
Requires: system76/coreboot#15
Ref: pop-os/system76-acpi-dkms#4
=> acpi: Handle ACPI queries for charging thresholds

src/board/system76/common/kbscan.c
Only allow key presses to wake from S3 when the lid is open.
Resolves: #102
=> kbscan: Prevent wake when lid is closed

src/board/system76/addw2/include/board/keymap.h, src/board/system76/bonw14/include/board/keymap.h, src/board/system76/common/battery.c, src/board/system76/common/config.c, src/board/system76/common/include/board/battery.h, src/board/system76/common/include/board/config.h, src/board/system76/common/include/board/kbscan.h, src/board/system76/common/kbscan.c, src/board/system76/common/power.c, src/board/system76/darp5/include/board/keymap.h, src/board/system76/galp3-c/include/board/keymap.h, src/board/system76/gaze15/include/board/keymap.h, src/board/system76/lemp9/include/board/keymap.h, src/board/system76/oryp5/include/board/keymap.h, src/board/system76/oryp6/include/board/keymap.h
Reset EC configuration; Currently only battery charging thresholds.
To test:
- Plug into AC power
- Flash this firmware
- Modify charging thresholds
- Power off and on
- Confirm charging thresholds are unchanged
- Power off
- Hold Fn+Esc and press power button to power on
- Once the power LED turns green, they can be released
- Confirm charging thresholds have reset to 0 and 100
=> Reset EC config if Fn+Esc held during power on

doc/mega2560.md
=> Typo: "not be be provided" -> "not be provided"

src/board/system76/addw1/include/board/keymap.h, src/board/system76/addw2/include/board/keymap.h, src/board/system76/darp5/include/board/keymap.h, src/board/system76/gaze15/include/board/keymap.h, src/board/system76/oryp5/include/board/keymap.h, src/board/system76/oryp5/keymap/default.c, src/board/system76/oryp6/include/board/keymap.h, src/common/include/common/keymap.h, tool/Cargo.lock, tool/Cargo.toml, tool/src/ec.rs, tool/src/lib.rs
The UK layout is simple, just specifying which keys should be international keys. We won't support remapping those keys, yet. The work to allow remapping can be done entirely in the keyboard configurator. I have also synced other compatible layouts, in case international keyboards are ever used on those.
And I updated ectool to improve SPI performance. It is on par with performance prior to abstracting the backend. I will need to cargo publish after this is rebased.
=> Improve ectool performance and implement darp6 UK layout

src/common/include/common/i2c.h
The `__reentrant` keyword introduced in common code is for SDCC.
=> Fix compilation on AVR

src/arch/8051/arch.mk, src/arch/avr/arch.mk, src/board/system76/common/flash/flash.mk, src/board/system76/common/scratch/scratch.mk
ROMs produced of Pop!_OS 20.10 and Fedora 33 with SDCC 4.0.0 cause uecflash to crash after verifying the block write, leaving the  system unbootable until all power is removed to force an EC reset.
Sorting object files appears to resolve this issue, creates a smaller binary (~200 bytes from 20.04), and gives more reproducible builds.
Resolves: system76/firmware-update#26
=> Sort object files

tool/src/access/hid.rs, tool/src/access/lpc/linux.rs, tool/src/access/lpc/mod.rs, tool/src/access/lpc/sim.rs, tool/src/error.rs
With this and https://github.com/system76/ecsim/pull/1, `system76_ectool info` at least can run, after changing `main.rs` to use `AccessLpcSim` insead of `AccessLpcLinux`.
=> ectool: AccessLpcSim for communicating with ecsim

src/board/system76/lemp10/gpio.c
I've flashed this using a USB stick many times and have seen the behavior I expect
=> lemp10: Set DPWROK low on EC reset to ensure PCH reset

doc/flashing.md
Replace the vague step about grounding with one that says to connect a USB cable and explain its purpose.
=> docs: Explicitly mention to use a USB cable

tool/LICENSE
`Cargo.toml` declares MIT license, but the included LICENSE is the ICU variant. Replace the text, as formatted on [choosealicense](https://choosealicense.com/licenses/mit/).
=> ectool: Replace ICU license with MIT license

.github/workflows/ci.yml, scripts/ectool.sh, scripts/power.sh, scripts/spdx.sh, src/board/system76/common/keymap.c, tool/src/access/hid.rs, tool/src/access/lpc/direct.rs, tool/src/access/lpc/linux.rs, tool/src/access/lpc/mod.rs, tool/src/access/lpc/sim.rs, tool/src/access/mod.rs, tool/src/ec.rs, tool/src/error.rs, tool/src/firmware.rs, tool/src/legacy.rs, tool/src/lib.rs, tool/src/main.rs, tool/src/pmc.rs, tool/src/spi.rs, tool/src/super_io.rs, tool/src/timeout.rs
- Add missing SPDX identifiers to source files
- Add a simple script to check for missing identifiers
- Add a CI job to check for missing identifiers
=> Add missing SPDX identifiers

scripts/deps.sh
Saves time and prevents errors with trying to install rustup twice or potentially overriding the user's default toolchain.
=> deps: Skip installing Rust if rustup is available

src/board/system76/common/kbscan.c, src/board/system76/common/pmc.c
This might fix issues with the oryp7 missing SCI events. It will need testing on multiple models and inspection of the kernel logs for errors. I threw in a change to not repeat K_FAN_TOGGLE, which I found while testing this.
=> Always notify OS of SCI when pmc_sci is called

rust-toolchain, scripts/deps.sh
rustup 1.23.0 (2020-11-27) introduced support for TOML syntax for the
toolchain file. Use this and specify required compoenents.
To ensure you are using a new enough rustup, run:
rustup self update
=> Convert toolchain file to TOML syntax

scripts/deps.sh, tool/Cargo.lock, tool/Cargo.toml, tool/src/access/lpc/direct.rs, tool/src/access/mod.rs
This allows the Configurator to send a `Ec<Box<dyn Access>>` through a channel to a background thread. This could be done differently, but presumably there's no reason to have an `Access` implementation this oesn't apply to.
=> tool: Make `Access` require `Send` and `'static` 

src/board/system76/common/dgpu.c, src/board/system76/common/fan.c, src/board/system76/common/include/board/dgpu.h, src/board/system76/common/include/board/fan.h, src/board/system76/common/include/board/peci.h, src/board/system76/common/main.c, src/board/system76/common/peci.c, src/board/system76/common/pwm.c, src/board/system76/galp5/board.mk
Fix for https://github.com/system76/firmware-open/issues/148
This PR adds support for new build flags:
- `SYNC_FANS` will read target fan speeds from both CPU and GPU fan curves, take the max and set both fans to this speed.
=> Sync dGPU and PECI fans (at highest requested duty)

README.md, doc/keyboard-layout-customization.md
I overlooked the first paragraph in the keyboard customization readme and jumped directly to the build steps so that I missed to install the build dependencies. Additionally, as `rustup` wasn't installed on my machine, I had to `source $HOME/.cargo/env` because I didn't restart the shell between `./scripts/dev.sh` and `make flash_internal`.
This PR updates the installation instructions.
=> Update keyboard customization instructions

src/board/system76/common/kbc.c
Fix ACPI timeout and delay on S3 resume when holding a key.
```
[ 3368.051132] ACPI: Waking up from system sleep state S3
[ 3369.136271] ACPI: EC: interrupt unblocked
[ 3370.249561] ACPI: EC: event unblocked
```
Tested on: oryp5, oryp6
While a timeout of 5ms was sufficient to fix the ACPI error, a value greater than 1ms (tested with 1.5ms and 2ms) still results in the excessive delay (~10s).
Resolves: #187
May also address system76/firmware-open#156
=> kbc: Reduce timeout from 10ms to 1ms

src/board/system76/common/kbc.c, src/ec/it5570e/include/ec/ps2.h, src/ec/it5570e/ps2.c, src/ec/it8587e/include/ec/ps2.h, src/ec/it8587e/ps2.c
When using I2C HID, the touchpad stops responding over PS/2. We should ensure this minimally affects other parts of the EC firmware
=> Make touchpad access non-blocking

scripts/deps.sh
ectool uses hidapi, which requires `cc` and `pkg-config` to be available.
This fixes building ectool on a minimal install system.
```
cargo build --manifest-path ecflash/Cargo.toml --example isp --release
```
Tested on:
- Ubuntu Server 20.04
- Fedora Server 34 ("Minimal Install" environment)
- Arch Linux
=> Add hidapi deps

src/board/system76/addw1/board.c, src/board/system76/addw2/board.c, src/board/system76/bonw14/board.c, src/board/system76/common/include/board/board.h, src/board/system76/common/include/board/power.h, src/board/system76/common/power.c, src/board/system76/darp5/board.c, src/board/system76/darp7/board.c, src/board/system76/galp3-c/board.c, src/board/system76/galp5/board.c, src/board/system76/gaze15/board.c, src/board/system76/lemp10/board.c, src/board/system76/lemp9/board.c, src/board/system76/oryp5/board.c, src/board/system76/oryp6/board.c, src/board/system76/oryp7/board.c
Logic for changing power limit is the same for all boards with GPUs. It is still called from `board_event()` instead of in `power_event()` to maintain the current behavior of checking every main cycle.
=> Move power limit functions to common board code

src/board/system76/addw2/board.c, src/board/system76/bonw14/board.c, src/board/system76/common/gctrl.c, src/board/system76/darp7/board.c, src/board/system76/galp5/board.c, src/board/system76/gaze15/board.c, src/board/system76/lemp10/board.c, src/board/system76/oryp6/board.c, src/board/system76/oryp7/board.c, src/ec/it5570e/ec.c, src/ec/it5570e/include/ec/ec.h
Logic for reading port 0x80/0x81 is common to the IT5570E. Define a EC function for reading POST codes and have the boards call that.
=> Move POST code logic from boards to EC

src/board/system76/common/include/board/kbc.h, src/board/system76/common/kbc.c, src/board/system76/common/kbscan.c
This should reduce the possibility of missed scancodes, especially inside UEFI.
=> Implement scancode buffer

src/arch/avr/i2c.c, src/board/system76/common/fan.c, src/board/system76/common/include/board/parallel.h, src/board/system76/common/kbled.c, src/board/system76/common/kbscan.c, src/board/system76/common/keymap.c, src/board/system76/common/main.c, src/board/system76/common/parallel.c, src/board/system76/common/power.c, src/common/i2c.c, src/common/include/common/i2c.h, src/common/include/common/keymap.h, src/ec/ite/i2c.c, src/ec/ite/include/ec/kbc.h, src/ec/ite/kbc.c
Ref: #222
```diff
--- build/system76/gaze15/2021-08-02_99af8a3/ec.mem     2021-08-02 12:14:45.885302912 -0600
+++ build/system76/gaze15/2021-08-02_6eff43f/ec.mem     2021-08-02 12:15:02.065163105 -0600
@@ -1,12 +1,12 @@
Internal RAM layout:
0 1 2 3 4 5 6 7 8 9 A B C D E F
0x00:|0|0|0|0|0|0|0|0|a|a|a|a|a|a|b|b|
-0x10:|b|b|b|b|b|b|b|b|b|b|b|b|b|c|c|c|
-0x20:|c|c|c|c|c|c|c|d|e|e|e|e|e|e|e|e|
-0x30:|f|f|g|g|g|g|g|g|g|g|g|g|g|g|g|g|
-0x40:|g|g|g|g|g|g|g|g|g|g|g|g|g|g|g|g|
-0x50:|g|h|i|i|i|i|i|i|i|i|i|i|Q|Q|Q|Q|
-0x60:|Q|S|S|S|S|S|S|S|S|S|S|S|S|S|S|S|
+0x10:|b|b|b|b|b|b|b|b|b|b|b|b|c|c|c|c|
+0x20:|d|e|e|e|e|e|e|e|e|f|f|f|f|f|f|f|
+0x30:|f|f|f|f|f|f|f|f|f|f|f|f|f|f|f|f|
+0x40:|f|f|f|f|f|f|f|f|g|h|h|h|h|h|h|h|
+0x50:|h|h|h|Q|Q|Q|Q|Q|S|S|S|S|S|S|S|S|
+0x60:|S|S|S|S|S|S|S|S|S|S|S|S|S|S|S|S| …
```
=> Use unsigned, shorter data types

doc/flashing.md
ecflash has no verification for the EC it detects. It will attempt to read and erase whatever it finds, where it will hang. Document what it *should* read and an example of what it *shouldn't* read.
=> docs: Only 5570 and 8587 are valid EC IDs

src/board/system76/common/main.c, src/board/system76/common/parallel.c, src/board/system76/common/power.c
Calculating diffs with *unsigned* integers will always produce the correct result, as long as the diff is less than the type max.
For example, suppose we read 254 and 2 for an 8 bit value:
2 - 254 = 4
Using this property, simplify diffs on `time_get()` comparisons.
=> Remove overflow check for unsigned diffs

src/board/system76/gaze16-3050/gpio.c, src/board/system76/gaze16-3060/gpio.c
This should make the gaze16 not require the AC adapter to be removed after flashing the EC.
=> gaze16: set PCH_DPWROK_EC low on EC boot to ensure PCH is off

src/common/include/common/command.h, tool/Cargo.lock, tool/Cargo.toml, tool/src/ec.rs, tool/src/main.rs
For testing Launch keyboards.
Could easily support in EC firmware as well if we had a use for that, but not adding that for now.
Requires https://github.com/system76/qmk_firmware/pull/20.
=> tool: Add a system76_ec command to disable input events

README.md
The IT81202E, despite using a different core, contains sufficiently
equivalent documentation to IT8587E and IT5570E for most tasks except
interrupt management. Provide it as a reference since we cannot share
the datasheets for the models we use.
=> readme: Add datasheet info

scripts/deps.sh
Ensure `rustup` is up-to-date to avoid users having a version that is too old to support the TOML format.
If rustup was just installed, tell the user to source the new env vars to use the correct version of the toolchain.
=> deps.sh: Update rustup or inform user of env vars

src/board/arduino/mega2560/parallel.c, src/board/system76/common/common.mk, src/board/system76/common/include/board/power.h, src/board/system76/common/kbscan.c, src/board/system76/common/main.c, src/board/system76/common/power.c
- Simplifies the power cycle code
- Ensures that if S0 is not reached, the system will fully power off which allows it to be retried
- Adds a special debug console that can attach to standard firmware but may miss some bytes
=> gaze16-3050 fix

src/board/system76/common/fan.c
SDCC is not able to optimize statics [\[1\]](https://sourceforge.net/p/sdcc/feature-requests/414/). Replace their use with defines so significantly better code is generated.
```diff
--- build/system76/oryp6/0/board/system76/common/fan.asm	2021-12-16 16:32:53.743631152 -0700
+++ build/system76/oryp6/1/board/system76/common/fan.asm	2021-12-16 16:43:13.537870374 -0700
@@ -1284,42 +1284,20 @@
mov	a,r6
subb	a,r7
jnc	00105$
-;	src/board/system76/common/fan.c:124: uint8_t smoothed = last_duty < MIN_FAN_SPEED + max_jump_down
-	push	ar6
-	mov	dptr,#_max_jump_down
-	clr	a
-	movc	a,@a+dptr
-	mov	r5,a
-	mov	r3,a
-	mov	r4,#0x00
-	mov	ar2,r7
-	mov	r6,#0x00
-	clr	c
-	mov	a,r2
-	subb	a,r3
-	mov	a,r6
-	xrl	a,#0x80
-	mov	b,r4
-	xrl	b,#0x80
-	subb	a,b
-	pop	ar6
+;	src/board/system76/common/fan.c:124: …
```
=> fan: Replace 'static const' with defines

src/board/system76/galp6/board.c, src/board/system76/galp6/gpio.c, src/board/system76/galp6/include/board/gpio.h
The schematics incorrectly show the pin as `USB_PWR_EN#`. There is a comment on the port side clarifying that it is actually active high.
Additionally, `PD_EN` is used instead of `VA_EC_EN` (like every other board) for enabling power to TCP0.
=> galp6: Fix USB power

src/board/system76/common/power.c, src/board/system76/galp6/gpio.c, src/board/system76/galp6/include/board/gpio.h
The previous commit incorrectly enabled power while off. Model `PD_EN` after `VA_EC_EN`, which it replaced on galp6 for TCP0.
Fixes: a6a6c5fba4fb ("galp6: Fix TCP0 power")
Power off and unplug the unit.
- Before change
- Power LED blinks orange, indicating CPU is powered
- Battery is drained over night
- After change
- Power LED remains off
- Battery is at the same capacity as before (probably <2% difference, due to powering off/on)
=> galp6: Do not provide power while off

src/board/system76/common/peci.c, src/board/system76/common/power.c, src/board/system76/darp7/board.mk, src/board/system76/darp8/board.mk, src/board/system76/galp5/board.mk, src/board/system76/galp6/board.mk, src/board/system76/gaze17-3050/board.mk, src/board/system76/gaze17-3050/gpio.c, src/board/system76/gaze17-3050/include/board/gpio.h, src/board/system76/gaze17-3060/board.mk, src/board/system76/gaze17-3060/gpio.c, src/board/system76/gaze17-3060/include/board/gpio.h, src/board/system76/lemp10/board.mk, src/board/system76/lemp11/board.mk, src/board/system76/oryp9/board.mk
S0ix does not require eSPI, and eSPI does not mandate S0ix.
Enable S0ix for:
- darp7 (TGL-U)
- darp8 (ADL-P)
- galp5 (TGL-U)
- galp6 (ADL-P)
- lemp10 (TGL-U)
- lemp11 (ADL-U)
It is also currently enabled on ADL-H due to a bug with S3:
- gaze17-3050
- gaze17-3060-b
- oryp9
=> Add config for using S0ix and fix detection

src/board/system76/common/battery.c
Change the condition, which is currently a level *at* which charging
will start/stop.
Per [sysfs](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power), these values are a level:
- *below* which charging will begin
- *above* which charging will stop
1. Set stop threshold
2. Drain battery ~5% below that value
3. Charge the battery
- Check: Battery shows the user specified value, not 1 below it
=> battery: Fix value to start/stop charging at

doc/mega2560.md
Having this list that we have to keep updated probably isn't ideal, but I figured I might as well update it now than I'm thinking about it.
=> Docs: update models that use 0.5mm pitch FPC cable

src/board/system76/common/pwm.c, src/ec/ite/include/ec/pwm.h
Add IT5570E register that controls when the down counters are updated. Set them to update when they reach 0, instead of immediately when DCRi is written.
Fixes keyboard color changing when changing brightness levels if not using 0xFF for an RGB value.
Fixes: #174
=> pwm: Reload counters when they reach 0

src/board/system76/common/acpi.c, src/board/system76/common/pmc.c, src/board/system76/lemp11/board.mk
lemp11 sometimes fails to reach C10 and gets stuck in C0 during s2idle. For some reason, sending a PMC SCI allows the CPU to go to C10.
Requires: system76/coreboot#142
=> HACK: pmc: Add hack to force S0ix entry on lemp11

src/arch/8051/arch.mk, src/arch/avr/arch.mk, src/board/system76/common/flash/flash.mk, src/board/system76/common/scratch/scratch.mk
Replace custom SDCC tool with the more standard binutils tool.
`scratch.rom` and `flash.rom` are different (no unnecessary padding), but resulting `ec.rom` is the same.
=> Replace makebin with objcopy

tool/src/main.rs
Adds newer launch versions to ec tool.
`sudo ./system76_ectool --access hid info` used to only work launch_1. This should now work with all current lanuch products.
Can be tested by plugging in each launch and running the above command, and/or
```bash
cargo build --release
sudo ./target/debug/system76_ectool --access hid led_mode 0 10 110
sudo ./target/debug/system76_ectool --access hid led_save
```
then plug and replug keyboard. LEDs should have saved.
=> Add other launch keyboards

src/board/system76/darp8/board.mk, src/board/system76/galp6/board.mk, src/board/system76/gaze17-3050/board.mk, src/board/system76/gaze17-3060/board.mk, src/board/system76/oryp9/board.mk
For some reason, *all* the ADL boards are now failing to enter S0ix. Apply the PMC hack to the remaining boards.
=> Apply hack for S0ix to all ADL boards

src/board/system76/common/power.c
This may fix issues with unresponsive power buttons.
=> Always power off if in S5 state on systems using eSPI

tool/Cargo.lock, tool/Cargo.toml
Fixes using as a dependency in no-std environments.
Ref: https://gitlab.redox-os.org/redox-os/hwio/-/merge_requests/5
=> tool: Disable default features of redox-hwio

Makefile, src/arch/8051/toolchain.mk
Allow specifying asm files the same way C files are added:
board-common-y += foo.asm
The file *must* use an `.asm` extension for 8051. The toolchain file filters the sources to compile them into objects correctly, as the C compiler doesn't handle asm files itself.
=> make: Enable compiling asm files

src/arch/avr/i2c.c, src/arch/avr/toolchain.mk
Compiling the Arduino targets with GCC 12 fails with the following:
error: array subscript 0 is outside array bounds of 'volatile uint8_t[0]' {aka 'volatile unsigned char[]'} [-Werror=array-bounds]
Apply the workaround from the bug discussion to fix it.
Ref: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105523
=> avr: Fix compiling with GCC 12

.github/workflows/ci.yml, Makefile, src/arch/8051/toolchain.mk, src/arch/avr/toolchain.mk, src/board/system76/common/flash/flash.mk, src/board/system76/common/scratch/scratch.mk
Default to silent builds, only outputting the file being generated. This gives output similar to Linux/coreboot output when building. `VERBOSE=1` can be passed to show the actual commands.
Example output:
```
$ make BOARD=system76/lemp10
CC        system76/lemp10/2023-01-13_7b75a7b/scratch/board/system76/common/scratch/../smfi.rel
CC        system76/lemp10/2023-01-13_7b75a7b/scratch/board/system76/common/scratch/main.rel
CC        system76/lemp10/2023-01-13_7b75a7b/scratch/board/system76/common/scratch/stdio.rel
LINK      system76/lemp10/2023-01-13_7b75a7b/scratch/scratch.ihx
OBJCOPY   system76/lemp10/2023-01-13_7b75a7b/scratch/scratch.rom
XXD       system76/lemp10/2023-01-13_7b75a7b/include/scratch.h
CC        system76/lemp10/2023-01-13_7b75a7b/flash/board/system76/common/flash/main.rel …
```
=> Reduce build output

.github/workflows/ci.yml, Makefile, src/arch/8051/toolchain.mk, src/arch/avr/toolchain.mk, src/board/system76/common/common.mk, src/board/system76/common/flash/flash.mk, src/board/system76/common/scratch/scratch.mk, src/keyboard/system76/14in_83/keyboard.mk, src/keyboard/system76/14in_86/keyboard.mk, src/keyboard/system76/15in_102/keyboard.mk, src/keyboard/system76/15in_102_nkey/keyboard.mk
SDCC supports the `-MMD` option. Use it instead of having every file depend on *all* the headers. Reduces incremental build time after modifying headers as it will now only rebuild the actual dependents and not the entire project.
=> Generate and use compiler dep rules

src/ec/ite/include/ec/intc.h, src/ec/ite/include/ec/wuc.h
Definitions for the INTC and WUC modules.
- IT8587E has INTC groups 0-18
- IT5570E has INTC groups 0-21
- WUC groups 1, 3, 4 have an extra register for enabling interrupts to INTC
=> Add INTC and WUC registers

src/board/system76/common/acpi.c, src/board/system76/common/pmc.c, src/board/system76/darp8/board.mk, src/board/system76/galp6/board.mk, src/board/system76/gaze17-3050/board.mk, src/board/system76/gaze17-3060/board.mk, src/board/system76/lemp11/board.mk, src/board/system76/oryp9/board.mk
Whatever the issue was appears to be fixed after rebasing coreboot on the 4.19 release. lemp11 has successfully reached S0ix with `SLP_S0#` asserted when booted on battery power for 100 cycles.
Requires: https://github.com/system76/coreboot/pull/160
=> Remove PMC hack for S0ix

rust-toolchain.toml, tool/Cargo.lock, tool/Cargo.toml
Update the toolchain and deps, and use the sparse registry access.
=> Update Rust toolchain to 2023-01-21

src/board/system76/common/kbc.c
Step 2 for data transmission (both RX and TX) is to enable the Transaction Done interrupt.
Ref: IT5570 V0.3.2, 7.9.3.1 Hardware Mode Selected
=> kbc: Enable Transaction Done interrupt

src/board/system76/common/peci.c, src/board/system76/common/power.c
- Check `FINISH` instead of `HOBY` for command completion
- Check hardware error bits (2, 3, 5, 6, 7) for hardware error
- Clear the status after command completion
- Log `WrPkgConfig()` errors in peci instead of power
TODO:
- Check if `peci_wr_pkg_config` error still happens when booting on battery power
=> peci: Fix waiting for completion and error checking

src/board/system76/common/common.mk, src/board/system76/common/peci.c, src/board/system76/oryp11/board.mk
Make all boards except oryp11 use the legacy PECI implementation. The oryp11 removed the legacy pin (`H_PECI`) and must use PECI over eSPI.
All boards that use eSPI should switch to using PECI over eSPI once the implementation is working correctly.
=> Only use PECI over eSPI on oryp11

src/board/system76/galp6/board.mk
Enable firmware security for galp7. Because the board is shared with galp6, that gets enabled as well.
=> galp6,galp7: Enable firmware security

src/board/system76/galp6/board.mk
Reduce PL4 to the same value as other non-GPU units, even though the galp7 has an H series CPU.
=> galp{6,7}: Reduce PL4 on AC to 65W

Makefile
Fixes building when `log.showSignature` is enabled.
See also: https://github.com/system76/firmware-open/pull/423
=> scripts: Disable showing signature when getting date

src/board/system76/darp9/gpio.c
Fixes using the non-TBT USB-C port.
=> darp9: Set CC_EN high

src/board/system76/common/peci.c
The PECI-over-eSPI implementation, like the legacy implementation, must acknowledge when the transaction is done by clearing the bit in the register.
Fixes a hang during shutdown on oryp11 after unplugging a TBT display.
TODO:
- Wait for any pending upstream transactions
=> peci: Clear status on completion

Makefile
From the man page:
%cs
committer date, short format (YYYY-MM-DD)
This is identical to what we use, without having to specify a custom date format for it.
=> Use `%cs` format when getting the commit date

src/board/system76/common/kbscan.c
Allows increased typing speed while avoiding repeating keys due to contact bounce and keys being rejected by ghost key detection.
This is also the default value for QMK.
Replaces: #359
=> kbscan: Reduce debounce time from 15ms to 5ms

src/board/system76/galp6/gpio.c, src/board/system76/lemp10/gpio.c, src/board/system76/lemp11/gpio.c, src/board/system76/lemp12/gpio.c
Tachometer should be configured as alternative function without pull.
=> Fix fan tach config

src/arch/8051/toolchain.mk, src/ec/ite/ec.mk
Ensure ROMs are the exact size of the flash device.
=> Pad binary file to total flash size

src/board/system76/common/include/board/kbc.h, src/board/system76/common/kbc.c, src/board/system76/common/power.c, src/ec/ite/include/ec/kbc.h
Should fix KBC being locked/disabled on boot.
TODO: Determine what is actually disabling it
=> Reset KBC on CPU reset

src/board/system76/addw2/gpio.c, src/board/system76/addw3/gpio.c, src/board/system76/bonw14/gpio.c, src/board/system76/bonw15/gpio.c, src/board/system76/darp7/gpio.c, src/board/system76/darp8/gpio.c, src/board/system76/galp5/gpio.c, src/board/system76/galp6/gpio.c, src/board/system76/gaze15/gpio.c, src/board/system76/gaze16-3050/gpio.c, src/board/system76/gaze16-3060/gpio.c, src/board/system76/gaze17-3050/gpio.c, src/board/system76/gaze17-3060/gpio.c, src/board/system76/lemp10/gpio.c, src/board/system76/lemp11/gpio.c, src/board/system76/oryp11/gpio.c, src/board/system76/oryp6/gpio.c, src/board/system76/oryp7/gpio.c, src/board/system76/oryp8/gpio.c, src/board/system76/oryp9/gpio.c
Enable PWRSW WDT 2 and use the default timeout of 10 seconds.
Allows forcing an EC reset in case it gets into an invalid state.
=> Enable power switch WDT on IT5570E boards

src/board/system76/common/kbscan.c
A single timer is used for debouncing all keys, so there is no reason to perform any operations if the matrix is being debounced. Just return early and remove some of the convoluted logic.
=> kbscan: Return early if debouncing

src/board/system76/addw1/gpio.c, src/board/system76/addw2/gpio.c, src/board/system76/addw3/gpio.c, src/board/system76/bonw14/gpio.c, src/board/system76/bonw15/gpio.c, src/board/system76/common/kbscan.c, src/board/system76/darp5/gpio.c, src/board/system76/darp7/gpio.c, src/board/system76/darp8/gpio.c, src/board/system76/galp3-c/gpio.c, src/board/system76/gaze15/gpio.c, src/board/system76/gaze16-3050/gpio.c, src/board/system76/gaze16-3060/gpio.c, src/board/system76/gaze17-3050/gpio.c, src/board/system76/gaze17-3060/gpio.c, src/board/system76/oryp11/gpio.c, src/board/system76/oryp5/gpio.c, src/board/system76/oryp6/gpio.c, src/board/system76/oryp7/gpio.c, src/board/system76/oryp8/gpio.c, src/board/system76/oryp9/gpio.c
Use the default mode for reading the keyboard scan matrix when being used as a keyboard. There should be no perceived change in behavior, but should make the code easier to understand.
Note: `KSO[17:16]` are configured by `GPRCRC` on boards that use them. They are now set to alternate function to use in KBS mode rather than GPIO mode, with the pull-up enabled to prevent them from floating when configured as open-drain.
As part of this change, we now only read the hardware matrix state once upfront, instead of on every iteration through the loop applying the logic.
Tested by cherry-picking to darp9 and verifying that typing still worked.
Need to test:
TODO:
- I don't notice any difference
=> kbscan: Switch from GPIO mode to KBS (Normal) mode

src/board/system76/common/kbscan.c, src/board/system76/common/keymap.c, src/common/include/common/keymap.h, src/keyboard/system76/14in_83/include/board/keymap.h, src/keyboard/system76/14in_86/include/board/keymap.h, src/keyboard/system76/15in_102/include/board/keymap.h, src/keyboard/system76/15in_102_nkey/include/board/keymap.h, src/keyboard/system76/18H9LHA04/include/board/keymap.h, src/keyboard/system76/18H9LHA05/include/board/keymap.h
Implement a FnLock toggle and a custom key for it.
- When disabled, `F1`-`F12` behave normally
- When enabled, `F1`-`F12` behave as the alternate function
Set it to `Fn+Esc` by default.
NOTE: Holding `Fn+Esc` at power on (S5 to S0) is used for resetting the EC configs. After S0, `Fn+Esc` will only act as FnLock.
NOTE: System76 laptops do not have an indicator for FnLock state.
Resolves: system76/firmware-open#78
=> Add FnLock key

docs/debugging.md
Relates to https://github.com/system76/ec/issues/374
=> add console_internal debugging instructions

src/board/system76/common/kbscan.c
Some users are reporting that a debounce time of 5ms is not enough to prevent keys from registering twice. Split the difference between the old and the new debounce times and set it to 10ms.
Ref: https://github.com/system76/firmware-open/issues/471
=> kbscan: Increase debounce time from 5ms to 10ms

src/board/system76/common/pnp.c, src/common/include/common/version.h, src/common/version.c
You may be using an older version, or perhaps recently set a -Werror type cflag, but the current master fails to build without this adjustment.
=> Fix sdcc error 283 - "function declarator with no prototype"

rust-toolchain.toml, tool/Cargo.lock, tool/Cargo.toml, tool/src/access/lpc/linux.rs, tool/src/access/lpc/sim.rs, tool/src/ec.rs, tool/src/main.rs, tool/src/spi.rs
- Update toolchain to nightly-2023-09-07
- Update edition to 2021
- Update deps
- Derive `Eq`, `PartialEq` on enums to allow comparisons with `==`
`OpenHidDeviceError` is deprecated, and is removed in newer versions. Replace it with `HidApiErrorEmpty`, because there are no descriptions for what anything means so I just picked one that didn't require fields.
Fix:
- `clippy::unnecessary_cast`
- `clippy::needless_borrow`
Allow:
- `clippy::uninlined_format_args`
- `clippy::get_first`
=> tool: Update toolchain, edition, deps

src/arch/avr/toolchain.mk
Apply the CFLAGS workaround for GCC 13.
The issue is fixed in GCC 14, so only 12 and 13 are affected.
Ref: 84fe76cad47d ("avr: Fix compiling with GCC 12")
Ref: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105523
=> avr: Fix compiling with GCC 13

src/board/system76/common/peci.c
Add timeouts to the legacy PECI implementation to prevent the EC locking up when PECI stops working, such as during S0ix opportunistic suspend.
This is not the optimal solution, as PECI should not be available at all to cause the lock up in the first place, but it at least prevents the issue.
Test:
Resolves: #412
Ref: #389
=> peci: Add timeouts to infinitely blocking waits

Makefile, src/arch/8051/toolchain.mk, src/arch/avr/toolchain.mk, src/board/system76/common/flash/flash.mk, src/board/system76/common/scratch/scratch.mk
As a follow up to c461e20df364 ("make: Remove version from build output path"), only support building a single version of a single board by default. The build directory can still be specified by passing `BUILD`.
Fixes running the `clean` target when `BUILD` is a custom value or `BOARD` isn't set.
Fixes: b03c960b4f52 ("make: Reduce build output")
=> Only support building a single board at a time

src/arch/avr/i2c_slave.c, src/arch/avr/include/arch/i2c_slave.h, src/arch/avr/include/arch/uart.h, src/arch/avr/uart.c, src/board/system76/addw1/gpio.c, src/board/system76/addw2/gpio.c, src/board/system76/addw3/gpio.c, src/board/system76/bonw14/gpio.c, src/board/system76/bonw15/gpio.c, src/board/system76/common/smfi.c, src/board/system76/darp5/gpio.c, src/board/system76/darp7/gpio.c, src/board/system76/galp3-c/gpio.c, src/board/system76/galp5/gpio.c, src/board/system76/gaze15/gpio.c, src/board/system76/gaze16-3050/gpio.c, src/board/system76/gaze16-3060/gpio.c, src/board/system76/gaze17-3050/gpio.c, src/board/system76/gaze17-3060/gpio.c, src/board/system76/gaze18/gpio.c, src/board/system76/lemp10/gpio.c, src/board/system76/lemp9/gpio.c, src/board/system76/oryp11/gpio.c, src/board/system76/oryp6/gpio.c, src/board/system76/oryp7/gpio.c, src/board/system76/oryp8/gpio.c
I don't know if any distro provides patch releases, because SDCC itself doesn't even bother to make releases for them (creates SVN tags, but no source tarballs). I built from the [SVN tag for 4.3.3](https://sourceforge.net/p/sdcc/code/HEAD/tree/tags/sdcc-4.3.3/) in a container and these were the errors.
Containerfile for testing:
<details>
<summary>Containerfile</summary>
```dockerfile
ARG CONTAINER_IMAGE="alpine:3.18.4"
FROM ${CONTAINER_IMAGE} as sdcc-build
ARG SDCC_REPO
ARG SDCC_REV
WORKDIR /tmp
RUN apk update && \
apk add --no-cache \
autoconf \
automake \
bison \
boost-dev \
ca-certificates \
flex \
g++ \
gcc \
make \
subversion \
zlib-dev
RUN svn checkout \
--depth infinity \
--revision ${SDCC_REV} \
${SDCC_REPO}/trunk/sdcc \
sdcc
RUN cd sdcc && \
sh ./configure \ …
```
=> Fix building with SDCC 4.3.3

tool/Cargo.lock, tool/Cargo.toml, tool/src/main.rs
I've found it annoying to add commands to `ectool`, which should be nicer with this. Plus more static checking.
=> ectool: Use clap derive for arg parsing

src/board/system76/common/kbscan.c
Pull the lid check out to the loop to avoid accessing the matrix when we know we do not need the data. It is left in kbscan (instead of simply disabling reading) to clear the state of the matrix data.
The lid check for wake is removed as it will never be true.
=> kbscan: Do not read matrix if lid is closed

src/board/system76/common/main.c
This prevents `moduint` from being called for the superloop.
A bitwise AND is used instead of using the equivalent `% 4` as an indication that modulo should not be used, as not using a power of 2 (which is optimized) will result in an expensive call to SDCC library functions.
=> main: Replace MOD with bitwise AND

src/board/system76/common/main.c
SDCC 4.4.0 now fails to compile if there are empty switch cases.
src/board/system76/common/main.c:105: error 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
Tested using #418.
=> main: Remove empty switch case

src/board/system76/addw4/board.mk
Development is sufficiently far along that this can default to enabled.
=> addw4: Enable security

scripts/deps.sh
Commit 17f8e37ed578 ("Convert toolchain file to TOML syntax") switched from the bare toolchain file to the TOML-based one for better management of the toolchain and components used.
Commit 1cb61e69186d ("deps.sh: Update rustup or inform user of env vars") added an explicit `rustup self update` because there were still cases, a year later, of people not having a rustup new enough to support the TOML-based toolchain file.
Now 2 years after that, it should be safe to drop the explicit self update. The TOML format has widespread adoption and rustup now self updates by default. This should allow distro-provided rustup, which disables the self update feature, to work if it is already installed in place of the one downloaded from https://rustup.rs.
=> scripts: Remove explicit rustup self update

.github/workflows/ci.yml
Fixes the following warnings in Actions:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3.
=> ci: Update actions/checkout to v4

rust-toolchain.toml
Update toolchain to match the version used in Redox.
=> tool: Update Rust toolchain to nightly-2024-05-11

src/board/system76/addw2/gpio.c, src/board/system76/addw3/gpio.c, src/board/system76/addw4/gpio.c, src/board/system76/bonw14/gpio.c, src/board/system76/bonw15/gpio.c, src/board/system76/darp7/gpio.c, src/board/system76/darp8/gpio.c, src/board/system76/darp9/gpio.c, src/board/system76/galp5/gpio.c, src/board/system76/galp6/gpio.c, src/board/system76/gaze15/gpio.c, src/board/system76/gaze16-3050/gpio.c, src/board/system76/gaze16-3060/gpio.c, src/board/system76/gaze17-3050/gpio.c, src/board/system76/gaze17-3060/gpio.c, src/board/system76/gaze18/gpio.c, src/board/system76/lemp10/gpio.c, src/board/system76/lemp11/gpio.c, src/board/system76/lemp12/gpio.c, src/board/system76/lemp13/gpio.c, src/board/system76/lemp9/gpio.c, src/board/system76/oryp11/gpio.c, src/board/system76/oryp12/gpio.c, src/board/system76/oryp6/gpio.c, src/board/system76/oryp7/gpio.c, src/board/system76/oryp8/gpio.c, src/board/system76/oryp9/gpio.c, src/board/system76/serw13/gpio.c, src/ec/ite/include/ec/gpio.h
On IT5570E, pin A1 is `VSTBY0` and not a GPIO pin.
=> Remove GPB7 on IT5570E

src/board/system76/common/kbc.c
This may fix ps2 touchpad support on Linux/Windows.
=> Fixes for touchpad

docs/flashing.md, docs/keyboard-layout-customization.md, scripts/ectool.sh, src/board/system76/common/security.c, tool/src/error.rs, tool/src/main.rs
Add a new error for the case of trying to flash when security is enabled and it is still locked and update the related docs.
=> tool: Add error for write locked

rust-toolchain.toml
Remove rust-src as it is not required. Use a minimal profile with clippy and rustfmt installed, instead of the default profile, as rust-docs is not needed.
=> Update Rust toolchain config

src/board/system76/common/include/board/peci.h, src/board/system76/common/peci.c
Resulting binary is identical.
=> Add enum for PECI command codes

src/arch/8051/include/arch/time.h, src/arch/8051/time.c, src/board/system76/common/kbscan.c, src/board/system76/common/main.c, src/board/system76/common/parallel.c, src/board/system76/common/peci.c, src/board/system76/common/power.c
The maximum interval when configured for a 1ms tick:
- 16-bit: ~65 seconds
- 32-bit: ~49.7 days
The value is used for scheduling and timeouts, and not to track the uptime of the system, so the 32-bit value is excessive.
<details>
<summary>oryp6 <code>ec.mem</code> diff</summary>
```diff
--- 0/ec.mem	2024-07-12 06:53:03.449950127 -0600
+++ 1/ec.mem	2024-07-12 06:53:15.068179591 -0600
@@ -1,11 +1,11 @@
Internal RAM layout:
0 1 2 3 4 5 6 7 8 9 A B C D E F
-0x00:|0|0|0|0|0|0|0|0|a|a|a|a|b|b|b|b|
-0x10:|b|b|c|c|c|c|c|c|c|c|c|c|c|e|g| |
-0x20:|B|B|B|d|d|d|d|f|f|f|f|f|f|f|f|f|
-0x30:|f|f|f|f|f|f|f|f|f|f|f|f|f|f|f|f|
-0x40:|f|f|f|f|f|f|h|h|h|h|h|h|h|h|h|h|
-0x50:|Q|Q|Q|Q|Q|S|S|S|S|S|S|S|S|S|S|S|
+0x00:|0|0|0|0|0|0|0|0|a|a|a|a|a|a|b|b|
+0x10:|b|b|b|b|b|b|b|b|b|c|c|c|c|e| | | …
```
=> Use a 16-bit system tick

src/board/system76/common/kbscan.c
IT8587E is hanging when reading the keyboard matrix.
- Increasing the delay does not fix it
- Placing delays between `KSO*` writes does not fix it
- Code generated by SDCC looks valid to me
Rewriting it like this does fix it, although I don't know why.
Tested on darp5 with WDT enabled:
- WDT is no longer triggered
- Normal EC functionality like fans and powering off works again
- Keyboard input still works
Resolves: #472
=> kbscan: Work around IT8587E hang

src/board/system76/addw1/gpio.c, src/board/system76/darp5/gpio.c, src/board/system76/galp3-c/gpio.c, src/board/system76/oryp5/gpio.c, src/ec/ite/include/ec/gpio.h
On IT8587E, pin 3 is VBAT and not a GPIO pin.
Ref: Table 4-1. Pins Listed in Numeric Order (128-pin LQFP)
Ref: Table 7-14. GPIO Alternate Function
=> Remove GPH7 on IT8587E

src/board/system76/bonw15-b/board.mk
The new Bonobo has the same pin layout as the original bonw15, but uses the larger IT5570E-256 instead of keeping the IT5570E-128.
**Impact**: Low
**Rationale**: New board that does not modify any common code.
=> bonw15-b: Add new Bonobo

src/board/system76/common/fan.c, src/board/system76/common/include/board/fan.h
Fans may be different sizes, placed in asymmetrical positions, or have different amounts of venting through the chassis. These characteristics affect the ability for each fan, separately, to dissipate heat and generate noise.
Replace syncing fans to the highest duty calculated for each fan, based on separate thermal sensors, to using the highest reported temperature across all sensors to calculate each fan's duty for that highest temperature.
In other words: The old behavior synced fans based on the *output* value (duty), while this new behavior syncs fans based on the *input* value (temperature).
This allows tuning fans separately to better manage total system thermals and mitigate noise.
Tested by modifying FAN2 points on oryp6 to always run at 80% and then verifying that "CPU fan" …
=> Sync fans based on temp instead of duty

src/board/system76/common/acpi.c, src/board/system76/common/battery.c, src/board/system76/common/flash/main.c, src/board/system76/common/include/board/battery.h, src/board/system76/common/keymap.c, src/board/system76/common/main.c, src/ec/ite/ec.mk
Make battery thresholds persistent by saving them in flash space. This allows configuring them after EC reset (system powered-off, unplugged) but before any system firmware or OS policy can be applied.
As part of this, the dynamic keymap is moved from the hard-coded address of 0x1FC00 to "the last sector"; Models with 256 KiB flash (`CONFIG_EC_FLASH_SIZE_256K=y`) will lose their layout and need to reconfigure it.
- When not configured, default values (90, 100) are used across multiple EC resets
- When configured, the profile/custom values are used across multiple EC resets
- If flash is dumped, the values are present in the ROM image
Check values with:
- `system76-power charge-thresholds`
- `cat /sys/class/power_supply/BAT0/charge_control_{start,end}_threshold`
=> Save battery thresholds to flash

src/board/system76/addw1/board.c, src/board/system76/addw2/board.c, src/board/system76/common/main.c, src/board/system76/common/power/intel.c
Rewrite the main loop to run all its events at certain intervals of the systick instead of running most on every loop.
- `usbpd_event`: Every 4 cycles -> 1ms
- `power_event`: Every 4 cycles -> 1ms
- `kbscan_event`: Every 4 cycles- > 5ms
- `lid_event`: Every 4 cycles -> 500ms
- `board_event`: Every cycle -> 1ms
- `kbc_event`: Every cycle -> 1ms
- `pmc_event`: Every cycle -> 1ms
- `smfi_event`: Every cycle -> 1ms
- `battery_event`: Every 1000ms
Ref: #209, Time-triggered architecture
=> main: Run events at time intervals

containers/Makefile, containers/ec/Containerfile
Add a command to create a Debian-based container with the SDCC and Rust toolchains installed in order to minimize the workspace setup time and ensure build environments are the same.
make -C containers
podman run -it --rm \
-v $PWD:/workspace:Z \
system76/ec:latest \
make BOARD=system76/oryp8
A locally built image is 1.07 GiB.
=> Add Containerfile for development

src/board/system76/common/acpi.c, src/board/system76/common/fan.c, src/board/system76/common/include/board/fan.h, src/board/system76/common/main.c, src/board/system76/common/smfi.c, src/common/include/common/command.h, tool/src/ec.rs, tool/src/lib.rs, tool/src/main.rs
Allow fan target duties to be set via ACPI or SMFI command. This will allow system firmware or OS to set fan duty, which can be used for testing or implementing user-defined fan tables.
Setting PWM via SMFI already existed, but would not work as the value would simply be overwritten by the EC.
RPM target is not supported.
Ref: system76/coreboot#245
Ref: system76/firmware-open#570
Ref: system76/firmware-open#571
=> Add manual fan control

scripts/deps.sh
- Use distro-provided rustup package on Fedora, Arch
- Use sh compatible commands where possible
- Update command for installing pinned Rust toolchain
- Remove progress messages
- Remove commands that conflict with running the script in other contexts
- git-hooks breaks calling from firmware-open directory
- submodule checkout is only required for external flashing and for generating initial board configs from firmware-open
=> scripts: Update `deps.sh`

docs/mega2560.md
Support had a customer asking about the pitch on a darp11, and I noticed this list could use an update. Hopefully darp10-b and darp11-b are clear enough about 0.5mm only being for the 14" model.
=> Update list of models that use 0.5mm keyboard FFC

docs/dev-env.md, src/arch/8051/toolchain.mk, src/board/system76/common/flash/flash.mk, src/board/system76/common/scratch/scratch.mk
Fedora installs SDCC to `/usr/libexec` and provides scripts in `/usr/bin` with the prefix `sdcc-`. Allow overriding SDCC name and setting a prefix.
Note: SDCC is broken on Fedora 42 and requires updating `PATH` explicitly anyways.
Link: https://bugzilla.redhat.com/show_bug.cgi?id=2344453
=> Allow SDCC to have a prefix
