system76/ec

README.md, doc/debugging.md, src/board/arduino/mega2560/parallel.c, src/board/arduino/uno/main.c, src/board/arduino/uno/parallel.c, src/board/system76/darp5/board.mk, src/board/system76/darp5/main.c, src/board/system76/darp5/stdio.c, src/board/system76/galp3-c/board.mk, src/board/system76/galp3-c/main.c, src/board/system76/galp3-c/stdio.c, src/board/system76/lemp9/board.mk, src/board/system76/lemp9/main.c, src/board/system76/lemp9/stdio.c, src/ec/it5570e/include/ec/parallel.h, src/ec/it5570e/parallel.c, src/ec/it8587e/include/ec/parallel.h, src/ec/it8587e/parallel.c
Implement logging over the parallel port.
- Add a command to the Mega to put it in peripheral mode and write logs from the EC to the serial port
- Implement host device logic in EC to write logs through parallel port
=> Debug logging over parallel port

src/board/system76/common/kbscan.c
=> Fix release of key after release of layer key

src/board/system76/common/kbscan.c
- Update debouncing code to properly handle rollover.
- Update ghost debouncing to properly set the debounce start time.
=> keymap: Improve debouncing behavior.

power.sh, src/board/system76/addw2/board.c, src/board/system76/addw2/board.mk, src/board/system76/addw2/dgpu.c, src/board/system76/addw2/gpio.c, src/board/system76/addw2/include/board/gpio.h, src/board/system76/common/include/board/peci.h, src/board/system76/common/peci.c, src/board/system76/gaze15/board.c, src/board/system76/gaze15/board.mk, src/board/system76/gaze15/dgpu.c, src/board/system76/gaze15/gpio.c, src/board/system76/gaze15/include/board/gpio.h, src/board/system76/oryp6/board.c, src/board/system76/oryp6/board.mk
This will get the addw2, gaze15, and oryp6 to set power limits when AC is plugged or unplugged. Also syncs improvements from oryp6 to addw2 and gaze15
=> Set power limits on AC plug event

src/board/system76/common/kbscan.c
=> kbscan: Disable key repeat for certain SCI keys

src/board/system76/addw2/gpio.c, src/board/system76/common/acpi.c, src/board/system76/common/dgpu.c, src/board/system76/common/include/board/dgpu.h, src/board/system76/darp5/gpio.c, src/board/system76/galp3-c/gpio.c, src/board/system76/lemp9/gpio.c
Please see notes on https://github.com/pop-os/system76-acpi-dkms/pull/3
=> Add ACPI thermal interface

src/board/system76/oryp5/gpio.c
=> oryp5: Fix speaker and headphone amps

doc/keyboard-layout-customization.md
This should hopefully help people avoid issues like #132
=> Add instructions for using released firmware version.

src/common/include/common/command.h, tool/Cargo.lock, tool/Cargo.toml, tool/src/ec.rs, tool/src/main.rs
See https://github.com/system76/qmk_firmware/pull/6.
=> tool: API and CLI for LED matrix mode

src/board/system76/common/include/board/kbscan.h, src/board/system76/common/kbscan.c, src/board/system76/common/smfi.c, src/common/include/common/command.h, tool/src/ec.rs, tool/src/main.rs
This will allow the configurator to read currently pressed keys
=> Add matrix command

tool/Cargo.lock, tool/Cargo.toml, tool/src/ec.rs, tool/src/main.rs
This is to support https://github.com/system76/qmk_firmware/pull/10. Will release as ectool 0.3.4 when approved
=> Add layer parameter for LED_GET_MODE and LED_SET_MODE commands

src/common/include/common/command.h, tool/Cargo.lock, tool/Cargo.toml, tool/src/ec.rs, tool/src/main.rs
For https://github.com/system76/qmk_firmware/pull/13
=> Add LED_SAVE command

src/board/system76/common/dgpu.c, src/board/system76/common/include/board/peci.h, src/board/system76/common/kbscan.c, src/board/system76/common/peci.c
=> Fixes for S0iX systems

src/board/system76/addw1/include/board/gpio.h, src/board/system76/addw2/include/board/gpio.h, src/board/system76/bonw14/include/board/gpio.h, src/board/system76/darp5/include/board/gpio.h, src/board/system76/darp7/include/board/gpio.h, src/board/system76/galp3-c/include/board/gpio.h, src/board/system76/galp5/include/board/gpio.h, src/board/system76/gaze15/include/board/gpio.h, src/board/system76/lemp10/include/board/gpio.h, src/board/system76/lemp9/include/board/gpio.h, src/board/system76/oryp5/include/board/gpio.h, src/board/system76/oryp6/include/board/gpio.h, src/board/system76/oryp7/include/board/gpio.h, src/ec/it5570e/include/ec/gpio.h, src/ec/it8587e/include/ec/gpio.h
Define GPCRn values once per EC, since they are not board-specific.
=> Define GPCRn values in EC header

README.md, doc/dev-env.md
Give an overview of the different tools required for development and what they're used for.
=> docs: Add overview of development environment

src/board/system76/addw1/board.c, src/board/system76/addw2/board.c, src/board/system76/bonw14/board.c, src/board/system76/darp5/board.c, src/board/system76/darp7/board.c, src/board/system76/galp3-c/board.c, src/board/system76/galp5/board.c, src/board/system76/gaze15/board.c, src/board/system76/lemp10/board.c, src/board/system76/lemp9/board.c, src/board/system76/oryp5/board.c, src/board/system76/oryp6/board.c, src/board/system76/oryp7/board.c
- lemp9: Remove duplicate setting of `XLP_OUT`
- Remove unused includes
- Remove unused extern declaration
=> Clean up board.c

src/board/system76/common/battery.c, src/board/system76/common/dgpu.c, src/board/system76/common/fan.c, src/board/system76/common/include/board/pnp.h, src/board/system76/common/peci.c, src/board/system76/common/pmc.c, src/board/system76/common/pnp.c, src/board/system76/common/power.c, src/board/system76/gaze16-3050/board.c, src/board/system76/gaze16-3050/board.mk, src/board/system76/gaze16-3050/gpio.c, src/board/system76/gaze16-3050/include/board/gpio.h, src/board/system76/gaze16-3060/board.c, src/board/system76/gaze16-3060/board.mk, src/board/system76/gaze16-3060/gpio.c, src/board/system76/gaze16-3060/include/board/gpio.h
Part of https://github.com/system76/firmware-open/pull/213
=> Add gaze16

src/board/system76/common/power.c
- Return false when power_peci_limit fails
- Allow power_peci_limit to be retried indefinitely from power_set_limit
Might fix gaze16 pl4 issues
=> Attempt to fix power_peci_limit issues

scripts/deps.sh, tool/Cargo.lock, tool/Cargo.toml
=> ectool: use linux-shared-hidraw feature for hidapi

rust-toolchain.toml, tool/Cargo.lock
Match the toolchain used by Redox.
Update dependencies and submodules to fix building.
=> Update Rust toolchain to 2022-03-18

src/board/system76/darp8/board.c, src/board/system76/darp8/board.mk, src/board/system76/darp8/gpio.c, src/board/system76/darp8/include/board/gpio.h, src/ec/ite/include/ec/gpio.h
=> Add Darter Pro 8

.github/workflows/ci.yml, src/board/system76/oryp9/board.c, src/board/system76/oryp9/board.mk, src/board/system76/oryp9/gpio.c, src/board/system76/oryp9/include/board/gpio.h
- system76/firmware-open#331
Fan points based on ODM-provided thermal data.
=> Add Oryx Pro 9

tool/Cargo.lock, tool/Cargo.toml, tool/src/main.rs
clap is only updated to 3.2 instead of 4.0 because I didn't want to deal with all the changes.
=> tool: Update dependencies

src/board/system76/bonw15/gpio.c
=> bonw15: invert USB power GPIO

src/ec/ite/ec.mk, src/ec/ite/include/ec/intc.h, src/ec/ite/include/ec/wuc.h, src/ec/ite/intc.c, src/ec/ite/wuc.c
This simplifies managing interrupts.
Ref: #209
=> Add functions to configure interrupts

src/ec/ite/include/ec/pmc.h, src/ec/ite/pmc.c
No functional change. Just adds the registers for managing PMC interrupts.
=> pmc: Add interrupt control and enable registers

src/board/system76/common/peci.c
If eSPI is used, use Virtual Wires to determine if PECI is available.
Fixes incorrectly reporting PECI as available on systems using S0ix, as the CPU would be in C10 but `PLTRST#` would not be asserted.
Requires enabling `HOST_C10` reporting in FSP-S: https://github.com/system76/coreboot/pull/189
Resolves: https://github.com/system76/firmware-open/issues/424
Test:
=> peci: Check PECI available based on eSPI usage

src/board/system76/common/pwm.c, src/ec/ite/ec.c, src/ec/ite/ec.mk, src/ec/ite/espi.c, src/ec/ite/i2c.c, src/ec/ite/include/ec/gctrl.h, src/ec/ite/include/ec/gpio.h, src/ec/ite/include/ec/i2c.h, src/ec/ite/include/ec/intc.h, src/ec/ite/include/ec/pwm.h, src/ec/ite/include/ec/smbus.h, src/ec/ite/intc.c
The IT5571E is nearly identical to the IT5570E.
Resolves: #391.
=> Add basic support for IT5571E

docs/flashing.md
=> docs: Add note about write lock for flashing

src/board/system76/common/kbscan.c
The functionality is split into a separate function to optimize the use case for each.
=> kbscan: Disable reading columns at init

src/board/system76/addw4/board.mk
Fixes: fff6208f9857 ("Conditionally compile KBLED support")
=> addw4: Enable KBLED support

src/board/system76/oryp12/board.mk
Probably fixes the charging issue.
=> oryp12: Use OZ26786 charger

src/board/system76/lemp13-b/board.c, src/board/system76/lemp13-b/board.mk, src/board/system76/lemp13-b/gpio.c, src/board/system76/lemp13-b/include/board/gpio.h
Copy of lemp13 with lemp12 keyboard
=> Add lemp13-b

src/board/system76/common/pnp.c
Use the sequence specified by the flowcharts in the ITE manuals.
Ref: IT5570E V0.3.2 datasheet; 7.15.5 EC2I Programming Guide
=> pnp: Match EC2I programming guide

src/board/system76/lemp13-b/gpio.c
Fixes: f79f4d115731 ("Remove GPB7 on IT5570E")
=> lemp13-b: Remove GPB7

tool/Cargo.lock, tool/Cargo.toml, tool/src/main.rs
I didn't check the docs. I just made it compile.
=> tool: Update clap to 4.5

.github/workflows/ci.yml
I regularly use the `.mem` file to determine the impact changes have on the RAM and flash usage. Print it as part of CI so I can easily see it for all boards.
=> ci: Show memory layout
